name: vayu_agent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  fluttertoast:
  another_flushbar: ^1.12.30
  dotted_border: ^2.0.0+3
  tab_container: ^3.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
